# -*- coding: utf-8 -*-
"""final_automatic_fake_news_prediction_bert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHZWsmoG3uNke5VacHT_YRKuY1H6Fs67
"""

import torch
from torch import nn
from transformers import AutoTokenizer, AutoModel

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

TOKENIZER_PATH = "best_tokenizer/"
MODEL_PATH = "best_fakenews_model.pt"

tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH)

class FakeNewsClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.bert = AutoModel.from_pretrained('distilbert-base-uncased')  # same as before
        self.classifier = nn.Sequential(
            nn.Linear(self.bert.config.hidden_size, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 2)
        )

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        return self.classifier(outputs.last_hidden_state[:, 0])

model = FakeNewsClassifier().to(device)
model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
model.eval()

def predict(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
        prediction = torch.argmax(outputs, dim=1).item()
    return "Fake" if prediction == 1 else "Real"

news_text = "Breaking: The president signs new healthcare reform bill"

print(predict(news_text))