# -*- coding: utf-8 -*-
"""fake_news_lstm_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hga4HpalPJNt6PEyV5FNfp7dELnqdLY3
"""

!pip install optuna --quiet

import optuna
from optuna.visualization import plot_optimization_history, plot_param_importances
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score, classification_report
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from tqdm.notebook import tqdm
import re
import nltk
from nltk.corpus import stopwords
from wordcloud import WordCloud
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
nltk.download('wordnet')
nltk.download('omw-1.4')

import kagglehub
path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")
fake = pd.read_csv(path + "/Fake.csv")
real = pd.read_csv(path + "/True.csv")
fake['label'] = 1
real['label'] = 0

data = pd.concat([fake, real], axis=0)
data = shuffle(data, random_state=42).reset_index(drop=True)

# Deduplicate
data = data.drop_duplicates().reset_index(drop=True)
data = data.drop_duplicates(subset=['text']).reset_index(drop=True)
data = data.drop_duplicates(subset=['title']).reset_index(drop=True)

data.head(10)

n_per_class = 5000
df_fake = data[data['label'] == 1].sample(n=n_per_class, random_state=42)
df_real = data[data['label'] == 0].sample(n=n_per_class, random_state=42)
data = pd.concat([df_fake, df_real]).sample(frac=1, random_state=42).reset_index(drop=True)

data['text_combined'] = data['title'] + " " + data['text']

lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(tokens)

data['preprocessed'] = data['text_combined'].apply(preprocess_text)

x_train, x_test, y_train, y_test = train_test_split(data['preprocessed'], data['label'], test_size=0.3, random_state=42)

from collections import Counter

def tokenize(text):
    return text.split()

word_counter = Counter()
for text in x_train:
    word_counter.update(tokenize(text))

vocab = {word: i+2 for i, (word, _) in enumerate(word_counter.most_common(20000))}
vocab['<PAD>'] = 0
vocab['<UNK>'] = 1

def encode(text, vocab, max_len=500):
    tokens = tokenize(text)
    encoded = [vocab.get(word, vocab['<UNK>']) for word in tokens[:max_len]]
    return encoded + [vocab['<PAD>']] * (max_len - len(encoded))

class FakeNewsDataset(Dataset):
    def __init__(self, texts, labels, vocab, max_len=500):
        self.texts = texts
        self.labels = labels
        self.vocab = vocab
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoded = encode(self.texts.iloc[idx], self.vocab, self.max_len)
        return torch.tensor(encoded, dtype=torch.long), torch.tensor(self.labels.iloc[idx], dtype=torch.long)

train_dataset = FakeNewsDataset(x_train, y_train, vocab)
test_dataset = FakeNewsDataset(x_test, y_test, vocab)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

class LSTMClassifier(nn.Module):
        def __init__(self, vocab_size, embed_dim, hidden_dim, dropout, output_dim=2):
            super(LSTMClassifier, self).__init__()
            self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
            self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
            self.dropout = nn.Dropout(dropout)
            self.fc = nn.Linear(hidden_dim, output_dim)

        def forward(self, x):
            x = self.embedding(x)
            _, (hidden, _) = self.lstm(x)
            x = self.dropout(hidden[-1])
            return self.fc(x)

def objective(trial):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Sample hyperparameters
    embed_dim = trial.suggest_categorical("embed_dim", [64, 128, 256])
    hidden_dim = trial.suggest_categorical("hidden_dim", [64, 128, 256])
    dropout = trial.suggest_float("dropout", 0.2, 0.5)
    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)  # Updated deprecated function


    model = LSTMClassifier(vocab_size=len(vocab), embed_dim=embed_dim, hidden_dim=hidden_dim, dropout = dropout).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    # Training
    model.train()
    for epoch in range(3):  # Keep short for tuning
        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

    # Evaluation
    model.eval()
    predictions, true_labels = [], []
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            preds = torch.argmax(outputs, dim=1).cpu().numpy()
            predictions.extend(preds)
            true_labels.extend(labels.numpy())

    return accuracy_score(true_labels, predictions)

study = optuna.create_study(direction="maximize", study_name = 'LSTM')
study.optimize(objective, n_trials=20)

# Best hyperparameters
print("Best trial:")
print(study.best_trial)

best_params = study.best_trial.params


final_model = LSTMClassifier(
    vocab_size=len(vocab),
    embed_dim=best_params["embed_dim"],
    hidden_dim=best_params["hidden_dim"],
    dropout=best_params["dropout"]
).to(device)

optimizer = torch.optim.Adam(final_model.parameters(), lr=best_params["lr"])
criterion = nn.CrossEntropyLoss()

# Train final model
for epoch in range(3):
    final_model.train()
    running_loss = 0.0

    # Use notebook-friendly tqdm here
    loop = tqdm(train_loader, desc=f'Epoch {epoch+1}', leave=True)

    for inputs, labels in loop:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = final_model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        loop.set_postfix(loss=running_loss / (loop.n + 1))

    print(f"Epoch {epoch+1} complete")

from sklearn.metrics import accuracy_score, classification_report
def evaluate(model, dataloader):
    model.eval()
    predictions, true_labels = [], []
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            preds = torch.argmax(outputs, dim=1).cpu().numpy()
            predictions.extend(preds)
            true_labels.extend(labels.numpy())
    acc = accuracy_score(true_labels, predictions)
    print("Classification Report:\n", classification_report(true_labels, predictions))
    return acc

train_acc = evaluate(final_model, train_loader)
print(f"Final train accuracy: {train_acc:.4f}")

test_acc = evaluate(final_model, test_loader)
print(f"Final test accuracy: {test_acc:.4f}")

def predict_fake_news(text, model, vocab, max_len=500):
    model.eval()
    cleaned = preprocess_text(text)
    encoded = encode(cleaned, vocab, max_len)
    tensor = torch.tensor(encoded, dtype=torch.long).unsqueeze(0).to(device)
    with torch.no_grad():
        output = model(tensor)
        pred = torch.argmax(output, dim=1).item()
    return "Fake" if pred == 1 else "Real"

# Example usage:
sample1 = df_real.iloc[657]['title'] + " " + df_real.iloc[657]['text']
sample2 = df_fake.iloc[256]['title'] + " " + df_fake.iloc[256]['text']
print("Prediction:", predict_fake_news(sample2, final_model, vocab))

save_path = 'lstm_fake_news_model.pth'
torch.save({
    'model_state_dict': final_model.state_dict(),
    'vocab': vocab,
    'params': best_params
}, save_path)